3.0.0 beta 6
crunchdao/crunch-cli pull request #43
Opened 2024-03-09 01:07 UTC by Caceresenzo

2024-03-09 01:08 UTC, Caceresenzo commented
Test are failing because the quickstarter feature has yet to be deployed in production.

2024-03-11 13:34 UTC, xaviergilbert approved these changes

2024-03-11 14:03 UTC, matteoettam09 requested changes

2024-03-11 14:03 UTC, matteoettam09 commented on tests/api/test_client.py
> +    # TODO Enable after production has quickstarter feature deployed
Can you uncomment this before we merge? I accepted the tournament PR

2024-03-11 14:50 UTC, matteoettam09 approved these changes

2024-03-11 14:51 UTC, merged