Submission hardcoded string
crunchdao/crunch-cli pull request #71
Opened 2024-06-18 13:47 UTC by Caceresenzo

## Features

- error: add `HardcodedStringFoundException`
  ```
  A hardcoded string value has been found, and your submission cannot be accepted.
  
  File Name: main.py
  String: "id"
  ```

## Refacto

- error: detect competition name from project

2024-06-18 14:57 UTC, xaviergilbert requested changes
Need to do the same for single quote

2024-06-19 21:16 UTC, jeheran requested changes
We accept this kind of submission just have a warning or keep context so we can send into the email this information.

2024-06-20 15:22 UTC, xaviergilbert approved these changes

2024-06-21 19:49 UTC, jeheran approved these changes

2024-06-24 09:10 UTC, merged